# Generated by Django 4.1.4 on 2023-10-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_rename_text_todolist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
