# Generated by Django 4.1.4 on 2023-10-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_remove_todolist_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
