# Generated by Django 4.1.4 on 2023-10-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='text2',
            field=models.CharField(default='Test', max_length=45),
        ),
    ]
