# Generated by Django 4.1.4 on 2023-10-14 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_todolist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='text2',
            new_name='name',
        ),
    ]
