# Generated by Django 4.1.4 on 2023-10-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_alter_todolist_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
    ]
